# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            查帥(Shuai)
tagline:          'Homepage'
description:      'Astrophysics, Comedy'
url:              http://joshuashzha.github.io
baseurl:          "http://joshuashzha.github.io"

author:
  name:           'Shuai'
  url:            

paginate:         5

# Custom vars
# version:          2.1.0

github:
  repo:          

gems:
  - jekyll-gist
