# Site settings
title: Shuai Zha
tagline:          'Homepage'
description:      'Astrophysics, Comedy'
email: dirk.nowi at gmail.com
#description: > # this means to ignore newlines until "baseurl:"
#  Thank you for visiting my website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  joshuashzha

# Build settings
markdown: kramdown
maruku:
  use_tex:    true

